workflows:
  development:
    name: Deploy to Development Environment
    triggering:
      events:                       # List the events that trigger builds
        - push
      branch_patterns:
        - pattern: 'development'
          include: true
      cancel_previous_builds: true
    environment:
      groups:
        - firebase_credentials
      vars:
        MY_BRANCH_NAME: $FCI_BRANCH
    scripts:
      - name: Check Current Branch
        script: |
          if [ "$MY_BRANCH_NAME" != "development" ]; then
            echo "Current branch is not 'development'. (current: $(git rev-parse --abbrev-ref HEAD)) Exiting..."
            # echo "Branch: $FCI_BRANCH -- $CM_BRANCH"
            exit 1  # This will fail the CI/CD pipeline
          fi
            echo "Current branch is 'development'. Continue with the CI/CD pipeline."
      - name: Current version of NPM
        script: |
          npm -v
      - name: NPM Clean and Get Dependencies
        script: |
          npm install
      - name: Check if Firebase CLI is installed
        script: |
          if ! command -v firebase &> /dev/null
          then
              echo "Firebase CLI not found. Installing..."
              npm install -g firebase-tools
          else
              echo "Firebase CLI is already installed."
          fi
      - name: Build Web Version
        script: |
          npm run build
      # - name: Archive artifacts
      #   script: |
      #     - mkdir -p $CM_BUILD_ARTIFACTS_DIR
      #     - cp -r dist/* $CM_BUILD_ARTIFACTS_DIR
      - name: Setting Up Google Service Account (Development Evnvironment)
        script: |
          echo "Copying Google Service Account data to:  $CM_BUILD_DIR"
          echo $FIREBASE_SERVICE_ACCOUNT_DEVELOPMENT > google_service_account.json
      - name: Publish to Firebase Hosting
        script: |
          firebase deploy --only hosting:fitflo-react-develop -m "Operator Portal deployed by test ci/cd workflow"
  